default: &default
  adapter: postgresql
  encoding: unicode
  # pool: 5
  # kindly replace your database user access
  username: postgres
  # kindly replace your database password
  password: 2604

development:
  <<: *default
  database: korikosun_App_development

test:
  <<: *default
  database: korikosun_App_backend_test
